name: "Install script tester"

on:
  push:
    branches: [ "dev" ]
    paths:
      - 'install.sh'

jobs:

  ubuntu:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Run install script
          run: sudo bash install.sh action